### ISSUE TITLE
Disclosures lack verbosity when viewed through Slack IRC Gateway

### ISSUE THREAD

**Issue by putsi** [bored-engineer/hackeroni-slack-disclosure-bot#10]
Currently disclosures look like following when viewed through the Slack IRC gateway:

```
16:08 < Xxxx_Disclosed> /reports/12345
06:50 < Yyyy_Disclosed> /reports/67890
````

If possible, it would be nice to have full URLs and maybe even the report title on the disclosure message.

**Comment by bored-engineer** [comment]
There's actually two issues here, the lack of full URLs is already being tracked in #9 and affects both the decorated messages and the IRC messages. 

In terms of message content I believe the IRC gateway messages are based on the fallback parameter: https://github.com/bored-engineer/hackeroni-slack-disclosure-bot/blob/0a10150365464d095078db3ed8a701dfcad7bb3e/main.go#L97

This should be an easy bug to fix once #9 is resolved.

**Comment by bored-engineer** [comment]
Whoops, GitHub thinks it's smart and auto-closed this. What are your thoughts on the change in a08762d? The new format should look like this:
```
<XYZ_Disclosed> "Report Title" - https://hackerone.com/reports/123456
```

**Comment by putsi** [comment]
It seems to work now, though it would be cool to see also severity and bounty like:
```
 <LocalTapiola_Disclosed> Medium - $60 - "Poodle attack SSLv3 Support (viestinta.lahitapiola.fi )" - https://hackerone.com/reports/181768
```
