### ISSUE TITLE
Add general support for Severity

### ISSUE THREAD

**Issue by putsi** [bored-engineer/hackeroni-slack-disclosure-bot#11]
It would be cool to have support for viewing Severity of disclosures (normal and IRC).

The IRC disclosure could also be re-factored to something like following:

```
 <LocalTapiola_Disclosed> Medium - $60 - "Poodle attack SSLv3 Support (viestinta.lahitapiola.fi )" - https://hackerone.com/reports/181768
```

**Comment by bored-engineer** [comment]
This would be a great feature, but it looks like I never added `Severity` support to the legacy package in the upstream H1 API client (https://github.com/uber-go/hackeroni). I've opened an issue to track support [here](https://github.com/uber-go/hackeroni/issues/19). After that has been resolved it should be a quick fix here.
